### ISSUE TITLE
Add source filename to TokenPosn

### ISSUE THREAD

**Issue by jeapostrophe** [quintenkasteel/language-javascript#102]
This would be a pretty invasive change, I think. One idea would be to make `TokenPosn` in `JSAnnot` a type parameter, then you could `fmap` over it and add the information on the filename lazily.

**Comment by erikd** [comment]
I don't think this is a good idea.

If you are only parsing a single file, then the file name is irrelevant. If you are parsing mulitple files, the it makes sense to keep track of the file name at the top of each file.

Now if you wanted to add a file name to one of the top level constructors, that would make sense, but even just adding a type parameter means that every `JSAnnot` constructor has an extra pointer.

What problem are you trying to solve?

**Comment by jeapostrophe** [comment]
I found a really simple way to track the file names. No problem!

**Comment by erikd** [comment]
Good news! Thanks @jeapostrophe .
