### ISSUE TITLE
the new version  doesn't compile on windows10.

### ISSUE THREAD

**Issue by idcm** [quintenkasteel/language-javascript#86]
The new version# works well on linux, but not compile on windows.
#language-javascript-0.6.0.12

**Comment by erikd** [comment]
You should probably post the error message here (text please, not a screen shot).

**Comment by idcm** [comment]
The error message when compile on Win10 :
--------------------------------------BEGIN-WIN10----------------------
PS C:\Users\dcm\Documents\language-javascript-0.6.0.12> stack init
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- .\

Selecting the best among 15 snapshots...

* Matches lts-13.21

Selected resolver: lts-13.21
Initialising configuration using resolver: lts-13.21
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
PS C:\Users\dcm\Documents\language-javascript-0.6.0.12> stack build
language-javascript-0.6.0.12: configure (lib)
Configuring language-javascript-0.6.0.12...
language-javascript-0.6.0.12: build (lib)
Preprocessing library for language-javascript-0.6.0.12..
happy.exe: src\Language\JavaScript\Parser\Grammar7.y: hGetContents: invalid argument (invalid byte sequence)

--  While building package language-javascript-0.6.0.12 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe --builddir=.stack-work\dist\e626a42b build lib:language-javascript --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
------------------------------------END--WIN10------------------------------

**Comment by erikd** [comment]
That is a problem with the Haskell tooling on Windows. It is not a problem with this project.

Since I do not use Windows, this is not something I can help you with. Sorry.

**Comment by idcm** [comment]
I find the problem. "hGetContents: invalid argument (invalid byte sequence)" comes from the symbol "∉" in "-- [ ]    export default [lookahead ∉ { function, class }] AssignmentExpression[In] ;" (line 1266 in \src\Language\JavaScript\Parser\Grammar7.y). If my understanding is right, this line is just a note and can be safely changed to somthing else, then all thing work well on win10. Maybe you can remove  "∉" in next version? Thanks.

**Comment by erikd** [comment]
I don't think that is a great solution. The happy parser is supposed to handle unicode fine. What version of happy are you using?

**Comment by idcm** [comment]
I use happy-1.19.10. I am not very familiar with Haskell, the document of 'hGetContents' shows that computation hGetContents hdl returns the list of characters corresponding to the unread portion of the channel or file managed by hdl.  This function is in base-4.12.0.0, may be its behavior is different in windows and linux. Any way, I know the problem, thanks.

**Comment by erikd** [comment]
Ok, that is a recent version of `happy`. This is some Windows specific thing with parts of the Haskell toolchain. Unfortunately, not being a Windows user, I cannot help.

**Comment by CGenie** [comment]
This isn't only windows. I get this on ArchLinux as well when compiling a yesod project:

```
Progress 13/67                    

--  While building package language-javascript-0.6.0.12 using:
      /home/przemek/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/przemek/yesod-test/.stack-work/logs/language-javascript-0.6.0.12.log

    Configuring language-javascript-0.6.0.12...
    Preprocessing library for language-javascript-0.6.0.12..
    happy: src/Language/JavaScript/Parser/Grammar7.y: hGetContents: invalid argument (invalid byte sequence)
```

It compiles fine when I add
```yaml
extra-deps:
  - language-javascript-0.6.0.11
```
to `stack.yaml`.

**Comment by erikd** [comment]
So it only happens with version 0.6.0.11 and doesn't happen with 0.6.0.12?

**Comment by mmilata** [comment]
Experiencing the same issue with 0.6.0.12 when building a yesod project on NixOS. Compiles fine with `resolver: lts-13.19` which has 0.6.0.11.

**Comment by erikd** [comment]
I don't use Nix and I do not use Windows. How do I reproduce this issue without either?

**Comment by hdgarrood** [comment]
This may be to do with your operating system locale. See https://github.com/purescript/purescript/pull/3640 for a similar issue with the PureScript parser. NixOS in particular seems to choose a silly default for locales which needs explicitly overriding, see e.g. https://github.com/purescript/purescript/pull/3639. We ended up addressing this by making our parser ASCII-only.

**Comment by erikd** [comment]
I don't think switching back to ASCII is an appropriate solution to this issue.

**Comment by hdgarrood** [comment]
Right, yes, I didn't mean to suggest otherwise. To answer your question: you may be able to reproduce this by setting your `LANG` environment variable to something like `en_US`.

**Comment by erikd** [comment]
Ok, I can recreate it using `LC_ALL=C cabal build`.

This is not a bug. Compiling `language-javascript` requires a UTF-8 locale.

**Comment by alx741** [comment]
I was having the exact same issue on FreeBSD (12.0-RELEASE), can confirm that using UTF8 in a locale like in `LC_ALL=en_US.UTF-8` fixes the build

**Comment by gukgurgel** [comment]
I was trying to build the yesod-postgres template and was having this same issue.
My LC_* were all set to C. I changed it to de_DE.UTF-8 and it built normally.

**Comment by joeyh** [comment]
I'm here because a user complained that my software failed to build because it has language-javascript as an indirect dependency. I assume they are using a non-unicode locale.

I noticed that ghc had the same problem back in 2013, in https://gitlab.haskell.org/ghc/ghc/-/issues/8167
There, the resolution was "happy reads .y files with the system encoding, so keep Parser.y.pp ASCII."

Breaking the non-zero number of users who still use a non-unicode locale makes me unhappy to have language-javascript as an indirect dependency. I do think that this may actually be a bug in happy, it is certianly *possible* to write haskell code that does not crash on these kinds of issues. But closing this bug without forwarding it to happy is not a good look.

**Comment by joeyh** [comment]
Found an open issue in happy about this, https://github.com/simonmar/happy/issues/157

**Comment by thatwist** [comment]
struggled with this.. this combo worked for me

```
echo "LC_CTYPE=\"en_US.UTF-8\"" | sudo tee -a /etc/default/locale
echo "LC_ALL=\"en_US.UTF-8\"" | sudo tee -a /etc/default/locale
echo "LANG=\"en_US.UTF-8\"" | sudo tee -a /etc/default/locale
echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
sudo locale-gen en_US.UTF-8
```
